### ISSUE TITLE
Simpler syntax

### ISSUE THREAD

**Issue by tailhook** [tomnomnom/gron#10]
Hi, 

This is such a great idea that I've decided to [port it to rust](https://github.com/tailhook/gron) because I need it as a library rather than a command-line tool (BTW, let me know if you want me to rename my version of the library)

The question is why there are semicolons? All javascript interpreters allow to skip them in all the cases in this subset of a javascript. I've decided to omit them, to have less visual noise, and make it easier to use `cut` and `awk` for the output. Is there any strong reason for your choice?

**Comment by tomnomnom** [comment]
Cool! I've not got much past the "hello world" stage with rust so it'll be really interesting to look at your source.

I think it would be a good idea to have a slightly different name for the package - not because I'm precious about it, but to make googling easier for users. Perhaps 'rust-gron' as per your license? :)

As for the semicolons: I've always been fairly strict about using them when writing JavaScript, mostly because I learnt JS in the days of IE5. That is to say: it's mostly habit. I'll look at maybe adding a flag to disable them if it gets enough interest.

Thanks!

**Comment by tomnomnom** [comment]
I haven't really had any interest in this so I'm going to close the issue.

I'm not saying never, but certainly not for now.
