### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by jcubic** [tomnomnom/gron#9]
I have 32bit GNU/Linux system how do I install gron?

**Comment by tomnomnom** [comment]
If you have a [Go environment](https://golang.org/doc/install) set up you can use:

```
go get -u github.com/tomnomnom/gron
```

I don't have a 32 bit machine to test on, but I've attached a custom 32 build for you here: [gron-linux-386-0.2.8.zip](https://github.com/tomnomnom/gron/files/399976/gron-linux-386-0.2.8.zip)

It's a zip rather than a tgz because github issues doesn't support tgz files apparently.

Let me know if that works for you and I'll look at adding 32 bit builds to the releases this evening.

**Comment by jcubic** [comment]
yes it work, but it's gzip file with zip extension.
